### ISSUE TITLE
WebhookとGithub Actionsは成功しているが、ビルド後の静的ファイルが反映されない

### ISSUE THREAD

**Issue by Hidetaro7** [Hidetaro7/neurona.jp#44]
以下のコマンドは成功する。
しかし `yarn build`した結果の静的ファイルが吐き出されていない、ブラウザで指定のパーマリンクを叩いてもエラーになる。

```
curl -X POST https://api.github.com/repos/Hidetaro7/neurona.jp/dispatches \
  -H 'Accept: application/vnd.github.everest-preview+json' \
  -u Hidetaro7:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \
  --data '{"event_type": "foo", "client_payload": { "customField": "customValue" }}'
```

**Comment by Hidetaro7** [comment]
やったこと

- Github Actionsの設定、Personal access tokensの取得
- Micro CMSでの設定も入力済み

期待したのに実現しなかった
- コマンドラインで叩いたらGithub Actionが走るが、Micro CMSでの記事更新などでは走らなかった
- コマンドラインで叩いてビルドしても、静的ファイルがGithub Pagesに存在しない、ただし、コンソール上には追加記事が読み込まれている

**Comment by knokmki612** [comment]
GitHub PagesへのGitHub Actionsでのデプロイは https://github.com/peaceiris/actions-gh-pages を使うのが便利です

**Comment by knokmki612** [comment]
> コマンドラインで叩いたらGithub Actionが走るが、Micro CMSでの記事更新などでは走らなかった

このドキュメントの案内を確認するとよいと思います https://document.microcms.io/manual/webhook-setting#hf0d425ae06

**Comment by Hidetaro7** [comment]
https://github.com/Hidetaro7/neurona.jp/commit/4aa1948f98e222abe4f388dd286ffb844bb1cfba

こうやって実現することができました。
Micro CMS側からの投稿でちゃんとGithub Actionが動いています。ありがとうございます。 @knokmki612
