### ISSUE TITLE
写真を補正

### ISSUE THREAD

**Issue by Hidetaro7** [Hidetaro7/neurona.jp#74]
@Tomo416 どの写真を差し替えてほしいか教えてくださいにゃ

**Comment by Tomo416** [comment]
上手になでろ、のところ[この写真に](https://www.dropbox.com/s/g3yh04d7rzi6p9u/tomo_03.jpg?dl=0)に差し替えてほしいですにゃ　@Hidetaro7 
<img width="1255" alt="スクリーンショット 2022-05-23 15 27 26" src="https://user-images.githubusercontent.com/57510486/169756934-b3637162-815d-4bbb-b1fe-cd6c28f24f95.png">

**Comment by Tomo416** [comment]
補正したのでクローズとする
